allow-expect-in-tests = true
allow-print-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
avoid-breaking-exported-api = false
excessive-nesting-threshold = 4
max-fn-params-bools = 1
