[package]
name = "win-nightlight-cli"
description = "Command-line tool to toggle and configure Windows 11 Night Light"
categories = ["command-line-utilities"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[[bin]]
name = "wnl"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
clap_complete = "4.6.11"
jiff = { version = "0.2.37", default-features = false, features = [
    "std",
    "tz-system",
    "tz-fat",
    "tzdb-bundle-platform",
] }
win-nightlight-lib.workspace = true

[lints]
workspace = true

[dev-dependencies]
hex-literal.workspace = true
insta = "1.49.0"
test-case.workspace = true
