[package]
name = "wnl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
win-nightlight-lib = { path = "../win-nightlight-lib" }
