[package]
name = "win-nightlight-lib"
description = "Read and modify Windows 11 Night Light state and settings in the registry"
categories = ["os::windows-apis"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []

[dependencies]
thiserror = "2.0.21"
windows-registry = "0.100.0"
windows-result = "0.100.0"

[lints]
workspace = true

[dev-dependencies]
hex-literal.workspace = true
proptest = "1.11.0"
test-case.workspace = true
